# 
# |               GitHub : https://github.com/HackTheCube/Discord                |
# -------------------------------------------------------------------------------- #
# |         _    _            _ _______ _           _____      _                 |
# |        | |  | |          | |__   __| |         / ____|    | |                |
# |        | |__| | __ _  ___| | _| |  | |__   ___| |    _   _| |                |
# |        |  __  |/ _` |/ __| |/ / |  | '_ \ / _ \ |   | | | | '_ \ / _ \       |
# |        | |  | | (_| | (__|   <| |  | | | |  __/ |___| |_| | |_) |  __/       |
# |        |_|  |_|\__,_|\___|_|\_\_|  |_| |_|\___|\_____\__,_|_.__/ \___|       |
# |                                                                              |
# -------------------------------------------------------------------------------- #
# |                   Discord : https://hackthecube.be/discord                   |
# 

# -------------------------------------------------------------------------------- #

GLOBAL:
   PREFIX:
      PREFIX: "&5&lHackTheCube &8&l×"
      ERROR: "&4&l(!)"
      
# -------------------------------------------------------------------------------- #

DISCORD:
   TOKEN: "-"
   
   STATUS: "DO_NOT_DISTURB"
   ACTIVITY:
      TYPE: "WATCHING"
      VALUE: "https://hackthecube.be/"